---
title: Foundation Events
description: Homepage for Foundation Events hosted at Samuel Morris Hall, Taylor University
author: Foundation
url: https://foundationevent.com
email: FoundationHauntedHouse@gmail.com

theme: null
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown

exclude:
  - .gitignore
  - README.md
  - .git/
  - "Page Template.md"
  - "Events/Event Template.md"

source: .
destination: _site

collections_dir: .
collections: {}

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: "en"
  - scope:
      path: "Page Template.md"
      type: "pages"
    values:
      sitemap: false
  - scope:
      path: "404.md"
      type: "pages"
    values:
      sitemap: false
  - scope:
      path: "Events/Event Template.md"
      type: "pages"
    values:
      sitemap: false
  - scope:
      path: "Events"
      type: "pages"
    values:
      layout: "event"
